//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_Source/InputSystem/MainActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace InputSystem
{
    public partial class @MainActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @MainActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainActions"",
    ""maps"": [
        {
            ""name"": ""Crowd"",
            ""id"": ""9cb4a957-fd19-4ade-8fef-80ef48b66d05"",
            ""actions"": [
                {
                    ""name"": ""SetDestination"",
                    ""type"": ""Button"",
                    ""id"": ""a8edc037-d479-43f6-ad6e-a9c0f83c4a93"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Destination"",
                    ""type"": ""Value"",
                    ""id"": ""1647187e-1b1c-44bb-a3b6-fc09e19603f1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""88ade68a-fbf0-4842-a70f-b2be7a2bb1c9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetDestination"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44b1f8a0-4df1-4387-ae15-e500df4f5bee"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Destination"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Crowd
            m_Crowd = asset.FindActionMap("Crowd", throwIfNotFound: true);
            m_Crowd_SetDestination = m_Crowd.FindAction("SetDestination", throwIfNotFound: true);
            m_Crowd_Destination = m_Crowd.FindAction("Destination", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Crowd
        private readonly InputActionMap m_Crowd;
        private ICrowdActions m_CrowdActionsCallbackInterface;
        private readonly InputAction m_Crowd_SetDestination;
        private readonly InputAction m_Crowd_Destination;
        public struct CrowdActions
        {
            private @MainActions m_Wrapper;
            public CrowdActions(@MainActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @SetDestination => m_Wrapper.m_Crowd_SetDestination;
            public InputAction @Destination => m_Wrapper.m_Crowd_Destination;
            public InputActionMap Get() { return m_Wrapper.m_Crowd; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CrowdActions set) { return set.Get(); }
            public void SetCallbacks(ICrowdActions instance)
            {
                if (m_Wrapper.m_CrowdActionsCallbackInterface != null)
                {
                    @SetDestination.started -= m_Wrapper.m_CrowdActionsCallbackInterface.OnSetDestination;
                    @SetDestination.performed -= m_Wrapper.m_CrowdActionsCallbackInterface.OnSetDestination;
                    @SetDestination.canceled -= m_Wrapper.m_CrowdActionsCallbackInterface.OnSetDestination;
                    @Destination.started -= m_Wrapper.m_CrowdActionsCallbackInterface.OnDestination;
                    @Destination.performed -= m_Wrapper.m_CrowdActionsCallbackInterface.OnDestination;
                    @Destination.canceled -= m_Wrapper.m_CrowdActionsCallbackInterface.OnDestination;
                }
                m_Wrapper.m_CrowdActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @SetDestination.started += instance.OnSetDestination;
                    @SetDestination.performed += instance.OnSetDestination;
                    @SetDestination.canceled += instance.OnSetDestination;
                    @Destination.started += instance.OnDestination;
                    @Destination.performed += instance.OnDestination;
                    @Destination.canceled += instance.OnDestination;
                }
            }
        }
        public CrowdActions @Crowd => new CrowdActions(this);
        public interface ICrowdActions
        {
            void OnSetDestination(InputAction.CallbackContext context);
            void OnDestination(InputAction.CallbackContext context);
        }
    }
}
